### ISSUE TITLE
[eslint-config] Update node rules config

### ISSUE THREAD

**Issue by MrTibbles** [IMGARENA/eslint-config#5]
Add the following rules to the `node-rules` config:

```json
  "rules": {
    "no-console": 0,
    "node/no-unsupported-features/es-syntax": ["error", {
      "version": ">=12.0.0",
      "ignores": ["modules"]
    }],
    "node/no-missing-import": ["error", {
      "tryExtensions": [".js", ".ts"]
    }]
  }
```

**Comment by johanlajili** [comment]
Bit more complex as you at least don't want no-console 0 on the client apps.
(Or do you? We can rediscuss this)

**Comment by MrTibbles** [comment]
These changes are for the node config, as the title says; they will not effect the client apps.

**Comment by MrTibbles** [comment]
These changes are for the node config, as the title says; they will not effect the client apps.
